# $Id: run1.mac,v 1.2 2000-11-21 10:59:42 maire Exp $
#
# Macro file for "exampleN03.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
/control/verbose 2
/control/saveHistory
#
/run/verbose 2
/event/verbose 0
/tracking/verbose 1
# 
# muon 300 MeV to the direction (1.,0.,0.)
# 3 events
#
/gps/particle e-
/gps/pos/centre -30.0 0.0 0.0 
/gps/direction 1 0 0
/gps/energy 1 GeV
/run/beamOn 1
